
//商品列表内容
var cmdListAll = [
	[
		{
			url:"https://www.baidu.com",
			src:"images/mi1.png",
			name:"小米9",
			price:"2999元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi2.png",
			name:"小米9SE",
			price:"1999元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi3.png",
			name:"小米8 青春版",
			price:"1499元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi4.png",
			name:"小米MIX3",
			price:"3299元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi5.png",
			name:"小米8",
			price:"2599元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi6.png",
			name:"小米Play",
			price:"1099元",
			tag:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/redmi1.jpg",
			name:"Redmi K20 Pro",
			price:"2499元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi2.jpg",
			name:"Redmi K20",
			price:"1999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi3.jpg",
			name:"Redmi 7A",
			price:"549元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi4.jpg",
			name:"Redmi Note 7 Pro",
			price:"1599元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi5.png",
			name:"Redmi Note 7",
			price:"999元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi6.png",
			name:"Redmi 7",
			price:"699元"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/television1.jpg",
			name:"小米壁画电视 65英寸",
			price:"6999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television2.jpg",
			name:"小米全面屏电视E55A",
			price:"2499元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television3.png",
			name:"小米电视4A 32英寸",
			price:"799元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television4.jpg",
			name:"小米电视4A 55英寸",
			price:"1999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television5.jpg",
			name:"小米电视4A 65英寸",
			price:"2999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television6.png",
			name:"查看全部",
			price:"小米电视"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/computer1.png",
			name:"RedmiBook 14",
			price:"3999元起",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer2.png",
			name:"小米笔记本 Air 12.5",
			price:"3499元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer3.png",
			name:"小米笔记本 Air 13.3",
			price:"4999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer4.png",
			name:"小米笔记本 15.6",
			price:"2999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer5.png",
			name:"小米笔记本 Pro 15.6",
			price:"4999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer6.png",
			name:"小米游戏本",
			price:"6499元"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/mi1.png",
			name:"小米9",
			price:"2999元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi2.png",
			name:"小米9SE",
			price:"1999元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi3.png",
			name:"小米8 青春版",
			price:"1499元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi4.png",
			name:"小米MIX3",
			price:"3299元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi5.png",
			name:"小米8",
			price:"2599元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/mi6.png",
			name:"小米Play",
			price:"1099元",
			tag:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/redmi1.jpg",
			name:"Redmi K20 Pro",
			price:"2499元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi2.jpg",
			name:"Redmi K20",
			price:"1999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi3.jpg",
			name:"Redmi 7A",
			price:"549元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi4.jpg",
			name:"Redmi Note 7 Pro",
			price:"1599元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi5.png",
			name:"Redmi Note 7",
			price:"999元"
		},
		{
			url:"https://www.baidu.com",
			src:"images/redmi6.png",
			name:"Redmi 7",
			price:"699元"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/television1.jpg",
			name:"小米壁画电视 65英寸",
			price:"6999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television2.jpg",
			name:"小米全面屏电视E55A",
			price:"2499元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television3.png",
			name:"小米电视4A 32英寸",
			price:"799元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television4.jpg",
			name:"小米电视4A 55英寸",
			price:"1999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television5.jpg",
			name:"小米电视4A 65英寸",
			price:"2999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/television6.png",
			name:"查看全部",
			price:"小米电视"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/computer1.png",
			name:"RedmiBook 14",
			price:"3999元起",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer2.png",
			name:"小米笔记本 Air 12.5",
			price:"3499元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer3.png",
			name:"小米笔记本 Air 13.3",
			price:"4999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer4.png",
			name:"小米笔记本 15.6",
			price:"2999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer5.png",
			name:"小米笔记本 Pro 15.6",
			price:"4999元",
			tag:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/computer6.png",
			name:"小米游戏本",
			price:"6499元"
		}
	]
]


//轮播图列表商品
var cateComAll = [
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		}
	],[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p2.jpg",
			name:"小米9"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9"
		}
	]
];



//家电选项卡商品列表
var dateComAll = [
	[
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url1:"https://www.baidu.com",
			name:"小米净水器终极版",
			price:"1999元",
			src:"./images/ca.png",
			url2:"https://www.baidu.com",
			more:"浏览更多",
			hot:"热门",
			icon:"&#xe615;"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"./images/television1.jpg",
			name:"小米电视",
			des:"64位四核处理器/1GB+4GB大内存",
			price:"799元",
			comment:{
				content:"山不再高，有仙则灵。电视不在大小，耐用就行。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/television1.jpg",
			name:"小米电视",
			des:"64位四核处理器/1GB+4GB大内存",
			price:"799元",
			comment:{
				content:"山不再高，有仙则灵。电视不在大小，耐用就行。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/television1.jpg",
			name:"小米电视",
			des:"64位四核处理器/1GB+4GB大内存",
			price:"799元",
			comment:{
				content:"山不再高，有仙则灵。电视不在大小，耐用就行。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/television1.jpg",
			name:"小米电视",
			des:"64位四核处理器/1GB+4GB大内存",
			price:"799元",
			comment:{
				content:"山不再高，有仙则灵。电视不在大小，耐用就行。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/television1.jpg",
			name:"小米电视",
			des:"64位四核处理器/1GB+4GB大内存",
			price:"799元",
			comment:{
				content:"山不再高，有仙则灵。电视不在大小，耐用就行。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/television1.jpg",
			name:"小米电视",
			des:"64位四核处理器/1GB+4GB大内存",
			price:"799元",
			comment:{
				content:"山不再高，有仙则灵。电视不在大小，耐用就行。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/television1.jpg",
			name:"小米电视",
			des:"64位四核处理器/1GB+4GB大内存",
			price:"799元",
			comment:{
				content:"山不再高，有仙则灵。电视不在大小，耐用就行。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url1:"https://www.baidu.com",
			name:"小米净水器终极版",
			price:"1999元",
			src:"./images/ca.png",
			url2:"https://www.baidu.com",
			more:"浏览更多",
			hot:"热门",
			icon:"&#xe615;"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"./images/mi1.png",
			name:"小米9",
			des:"",
			price:"2999元",
			comment:{
				content:"轻薄完美，深空灰超帅！",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mi1.png",
			name:"小米9",
			des:"",
			price:"2999元",
			comment:{
				content:"轻薄完美，深空灰超帅！",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mi1.png",
			name:"小米9",
			des:"",
			price:"2999元",
			comment:{
				content:"轻薄完美，深空灰超帅！",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mi1.png",
			name:"小米9",
			des:"",
			price:"2999元",
			comment:{
				content:"轻薄完美，深空灰超帅！",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mi1.png",
			name:"小米9",
			des:"",
			price:"2999元",
			comment:{
				content:"轻薄完美，深空灰超帅！",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mi1.png",
			name:"小米9",
			des:"",
			price:"2999元",
			comment:{
				content:"轻薄完美，深空灰超帅！",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mi1.png",
			name:"小米9",
			des:"",
			price:"2999元",
			comment:{
				content:"轻薄完美，深空灰超帅！",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url1:"https://www.baidu.com",
			name:"小米净水器终极版",
			price:"1999元",
			src:"./images/ca.png",
			url2:"https://www.baidu.com",
			more:"浏览更多",
			hot:"热门",
			icon:"&#xe615;"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url:"https://www.baidu.com",
			src:"./images/mihouseld.jpg",
			name:"米家电水壶",
			des:"一杯水，是一家人的安心",
			price:"99元",
			comment:{
				content:"变成忠实的米粉了，烧水很快声音也小。",
				from:"来自iphnexxxxxxxx的评价"
			}
		},
		{
			url1:"https://www.baidu.com",
			name:"小米净水器终极版",
			price:"1999元",
			src:"./images/ca.png",
			url2:"https://www.baidu.com",
			more:"浏览更多",
			hot:"热门",
			icon:"&#xe615;"
		}
	]
]